name: Upload to code artifactory


on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository code
        uses:  actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        run: |
          python setup.py sdist bdist_wheel
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: ${{ secrets.ROLE_SESSION_NAME }}
          role-duration-seconds: 900
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Publish package
        run: |
          aws codeartifact login --tool twine --domain FIX_ME_DOMAIN --repository FIX_ME_REPOSITORY && twine upload --repository codeartifact dist/*